[package]
name = "steam-game-idler"
version = "0.1.0"
authors = ["zevnda"]
license = "GPL-3.0"
repository = "https://github.com/zevnda/steam-game-idler"
default-run = "steam-game-idler"
edition = "2021"
rust-version = "1.60"

[build-dependencies]
tauri-build = { version = "1.5.2", features = [] }

[dependencies]
chrono = "0.4"
regex = "1.7.1"
select = "0.6.0"
dotenvs = "0.1.0"
scraper = "0.20.0"
serde_json = "1.0"
lazy_static = "1.5.0"
window-shadows = "0.2.2"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
reqwest = { version = "0.11", features = ["json"] }
winapi = { version = "0.3", features = ["processthreadsapi", "handleapi", "winnt"] }
tauri-plugin-autostart = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v1" }
tauri-plugin-window-state = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v1" }
tauri = { version = "1.6.5", features = [ "notification-all", "system-tray", "window-set-position", "window-set-size", "process-relaunch", "shell-open", "fs-all", "path-all", "dialog-ask", "updater", "window-start-dragging", "window-show", "window-hide", "window-close", "window-maximize", "window-minimize", "window-unmaximize", "window-unminimize"] }

steamlocate = "2.0.1"

[features]
custom-protocol = [ "tauri/custom-protocol" ]
