[package]
name = "steam-game-idler"
version = "0.1.0"
authors = ["zevnda"]
license = "GPL-3.0"
repository = "https://github.com/zevnda/steam-game-idler"
default-run = "steam-game-idler"
edition = "2021"
rust-version = "1.60"

[build-dependencies]
tauri-build = { version = "1.5.2", features = [] }

[dependencies]
dotenvs = "0.1.0"
scraper = "0.22.0"
lazy_static = "1.5.0"
steamlocate = "2.0.1"
window-shadows = "0.2.2"
tokio = { version = "1", features = ["full"] }
chrono = { version = "0.4.39", features = ["clock"] }
serde = { version = "1.0.217", features = ["derive"] }
reqwest = { version = "0.12.12", features = ["json"] }
serde_json = { version = "1.0.138", features = ["std"] }
regex = { version = "1.11.1", default-features = false, features = ["std"] }
winapi = { version = "0.3.9", features = ["processthreadsapi", "handleapi", "winnt"] }
tauri-plugin-autostart = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v1" }
tauri-plugin-window-state = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v1" }
tauri = { version = "1.6.5", features = [
    "fs-all",
    "updater",
    "path-all",
    "shell-open",
    "dialog-ask",
    "system-tray",
    "notification-all",
    "process-relaunch",
    "window-show",
    "window-hide",
    "window-close",
    "window-maximize",
    "window-minimize",
    "window-set-size",
    "window-unmaximize", 
    "window-unminimize",
    "window-set-position",
    "window-start-dragging"
] }

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
strip = false
panic = "abort"
overflow-checks = false

[features]
custom-protocol = ["tauri/custom-protocol"]
