name: Issue/Bug Report
description: Create an issue or bug report
title: "Check the FAQ wiki before reporting an issue - https://github.com/zevnda/steam-game-idler/wiki/faq"
labels: ["bug", "investigating"]
assignees:
  - "ProbablyRaging"
body:
  - type: checkboxes
    id: terms
    attributes:
      label: Pre-report checklist
      options:
        - label: I have checked for similar open/closed issues
        - label: I have checked the FAQ wiki for my issue
        
  - type: textarea
    id: description
    attributes:
      label: Describe the issue
      description: A clear and descriptive overview of your issue
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Provide detailed steps to reproduce your issue 

  - type: file
    id: log-file
    attributes:
      label: Log file
      description: Upload your "log.txt" file (located in "C:\Users\<user>\AppData\Roaming\steam-game-idler")
    validations:
      required: true

  - type: file
    id: screenshots
    attributes:
      label: Screenshots or videos
      description: Upload screenshots or screen recordings demonstrating the issue
      multiple: true
      
  - type: dropdown
    id: sgi-branch
    attributes:
      label: Which branch of SGI?
      options:
        - "Base"
        - "CLI + WebUI"
    validations:
      required: true
      
  - type: dropdown
    id: version
    attributes:
      label: What version of SGI are you using?
      description: If using an older version, specify which version in your issue
      options:
        - Latest version
        - Older version
    validations:
      required: true
