name: Issue/Bug Report
description: Create an issue or bug report
labels: ["bug"]
assignees:
  - "zevnda"
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the issue
      description: A clear and descriptive overview of your issue
      placeholder: Feel free to include any screenshots or videos that demonstrate your issue
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce the issue
      description: Provide detailed steps to reproduce your issue
      placeholder: Leave this blank if you are unsure

  - type: textarea
    id: log-file
    attributes:
      label: Provide your log file
      description: Useful for debugging issue
      placeholder: Use the attachment button below. Your log file can be found in "C:\Users\<user>\AppData\Roaming\steam-game-idler"

  - type: textarea
    id: export-data
    attributes:
      label: Provide your exported data
      description: Useful for debugging issue
      placeholder: You can export your data by going to Settings and clicking the Export Data button then pasting it here

  - type: dropdown
    id: sgi-version
    attributes:
      label: Steam Game Idler Version
      options:
        - "Latest release"
        - "Older release"
        - "Beta release"
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Pre-report checklist
      description: Please try to fulfull all of the following
      options:
        - label: I have checked for similar [open/closed issues](https://github.com/zevnda/steam-game-idler/issues)
          required: true
        - label: I have checked the [FAQ wiki](https://steamgameidler.vercel.app/faq) for my issue
          required: true
        - label: I have included my log file
        - label: I have included my exported data
