name: Issue/Bug Report
description: Create an issue or bug report
labels: ["bug", "investigating"]
assignees:
  - "zevnda"
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the issue
      description: A clear and descriptive overview of your issue
      placeholder: Feel free to include any screenshots or videos that demonstrate your issue 
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce the issue
      description: Provide detailed steps to reproduce your issue
      placeholder: Leave this blank if you are unsure
      
  - type: dropdown
    id: sgi-branch
    attributes:
      label: Which branch of SGI?
      options:
        - "Base"
        - "CLI + WebUI"
    validations:
      required: true
      
  - type: dropdown
    id: version
    attributes:
      label: What version of SGI are you using?
      description: If using an older version, specify which version in your issue
      options:
        - Latest version
        - Older version
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Pre-report checklist
      description: Please try to fulfull all of the following
      options:
        - label: I have checked for similar [open/closed issues](https://github.com/zevnda/steam-game-idler/issues?q=)
          required: true
        - label: I have checked the [FAQ wiki](https://github.com/zevnda/steam-game-idler/wiki/faq) for my issue
          required: true
        - label: I have included my "log.txt" file located in "C:\\Users\\your_username\\AppData\\Roaming\\steam-game-idler"
          required: true
