name: Mark stale issues and pull requests
on:
  schedule:
  - cron: '0 0 * * 0'
  workflow_dispatch:
jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/stale@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        days-before-stale: 7
        days-before-close: 0
        stale-issue-message: 'This issue is stale because it has been open for 7 days with no activity. Reply to this issue to re-open it.'
        stale-pr-message: 'This pull request is stale because it has been open for 7 days with no activity. Reply to this pull request to re-open it.'
        stale-issue-label: 'stale'
        stale-pr-label: 'stale'
        exempt-issue-labels: 'not stale'
        exempt-pr-labels: 'not stale'
